### ISSUE TITLE
GLFW compile error

### ISSUE THREAD

**Issue by Moneyl** [beefytech/Beef#1617]
Getting compile errors when using GLFW beef (https://github.com/MineGame159/glfw-beef). Issue cropped up some time between 0.43.3 and the current commit. It builds fine with 0.43.3. 
```
vdata.obj : error LNK2019: unresolved external symbol "public: static void __cdecl bf::GLFW::Glfw::GCMarkStaticMembers(void)" (?GCMarkStaticMembers@Glfw@GLFW@bf@@SAXXZ) referenced in function "private: static void __cdecl bf::System::GC::MarkAllStaticMembers(void)" (?MarkAllStaticMembers@GC@System@bf@@CAXXZ)
vdata.obj : error LNK2019: unresolved external symbol "public: static void __cdecl bf::GLFW::Glfw::__BfStaticDtor(void)" (?__BfStaticDtor@Glfw@GLFW@bf@@SAXXZ) referenced in function BfCallAllStaticDtors
c:\Users\moneyl\source\repos\BeefGlfwTest\build\Debug_Win64\BeefGlfwTest\BeefGlfwTest.exe : fatal error LNK1120: 2 unresolved externals
```

Attached an example project
[BeefGlfwTest.zip](https://github.com/beefytech/Beef/files/9006581/BeefGlfwTest.zip)

**Comment by bfiete** [comment]
Fixed at 45a0f774c70360695cbd3c6193b81d90d09d1f7e

**Comment by Moneyl** [comment]
Thank you
