### ISSUE TITLE
Could not build on Macos 10.14 Mojave

### ISSUE THREAD

**Issue by phillvancejr** [beefytech/Beef#120]
cloned repository and ran bin/build.sh, but got the following error:
```
Beef/BeefySysLib/util/String.cpp:126:20: error: out-of-line definition
      of 'LastIndexOf' does not match any declaration in 'Beefy::StringView'
intptr StringView::LastIndexOf(char c, intptr startCheck) const

1 error generated.
make[2]: *** [BeefySysLib/CMakeFiles/BeefySysLib.dir/util/String.cpp.o] Error 1
make[1]: *** [BeefySysLib/CMakeFiles/BeefySysLib.dir/all] Error 2
```

**Comment by bfiete** [comment]
There were a couple of Mac issues. Fixed in https://github.com/beefytech/Beef/commit/8709c92f2290bb0689bc0b229b3c28ce286507ff

**Comment by phillvancejr** [comment]
clone the new repo and this time got a different error
```
Building BeefBuild_bootd
[******************************]
TIMING: Beef compiling: 56.6s
Linking BeefBuild_bootd...Undefined symbols for architecture x86_64:
  "_ffi_call", referenced from:
      bf::System::FFI::FFILIB::Call(bf::System::FFI::FFILIB::FFICIF*, void*, void*, void**) in libBeefRT_d.a(Internal.cpp.o)
  "_ffi_closure_alloc", referenced from:
      bf::System::FFI::FFILIB::ClosureAlloc(long, void**) in libBeefRT_d.a(Internal.cpp.o)
  "_ffi_prep_cif", referenced from:
      bf::System::FFI::FFILIB::PrepCif(bf::System::FFI::FFILIB::FFICIF*, bf::System::FFI::FFIABI, int, bf::System::FFI::FFIType*, bf::System::FFI::FFIType**) in libBeefRT_d.a(Internal.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL: Exit code returned: 1

FAILED
```

**Comment by pmysl** [comment]
It looks like a problem with libffi. I solved it by installing libffi from Homebrew and adding a path to lib in `[Configs.Debug.macOS]` and `[Configs.Release.macOS]` sections of `BeefBuild/BeefProj.toml`. You can also use libffi bundled with Beef. You'll find it here: `BeefySysLib/third_party/libffi/x86_64-apple-darwin19.3.0/.libs/libffi.a`

**Comment by MichaelSDavid** [comment]
> It looks like a problem with libffi. I solved it by installing libffi from Homebrew and adding a path to lib in `[Configs.Debug.macOS]` and `[Configs.Release.macOS]` sections of `BeefBuild/BeefProj.toml`. You can also use libffi bundled with Beef. You'll find it here: `BeefySysLib/third_party/libffi/x86_64-apple-darwin19.3.0/.libs/libffi.a` (version in path may vary)

What do you mean by adding a path? What like variable name did you use? (I'm not the most familiar with TOML as you might be able to tell) I really want to fix this since Beef looks very exciting. I would like to know the exact text (excluding the exact path of libffi since that varies for every system, just say <libffi path> or something) you added to the file under `[Configs.Debug.macOS]` and `[Configs.Release.macOS]`

**Comment by MichaelSDavid** [comment]
> It looks like a problem with libffi. I solved it by installing libffi from Homebrew and adding a path to lib in `[Configs.Debug.macOS]` and `[Configs.Release.macOS]` sections of `BeefBuild/BeefProj.toml`. You can also use libffi bundled with Beef. You'll find it here: `BeefySysLib/third_party/libffi/x86_64-apple-darwin19.3.0/.libs/libffi.a` (version in path may vary)

@pmysl What do you mean by adding a path? What like variable name did you use? (I'm not the most familiar with TOML as you might be able to tell) I really want to fix this since Beef looks very exciting. I would like to know the exact text (excluding the exact path of libffi since that varies for every system, just say `<libffi path>` or something) you added to the file under `[Configs.Debug.macOS]` and `[Configs.Release.macOS]`

**Comment by pmysl** [comment]
This is how I changed `BeefProj.toml`. You should also add a path to libffi to `OtherLinkFlags` under `[Configs.Release.macOS]`

```diff
diff --git a/BeefBuild/BeefProj.toml b/BeefBuild/BeefProj.toml
index fa7ef21..dcd3ad1 100644
--- a/BeefBuild/BeefProj.toml
+++ b/BeefBuild/BeefProj.toml
@@ -27,7 +27,7 @@ PreprocessorMacros = ["DEBUG", "CLI"]
 [Configs.Debug.macOS]
 TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
 TargetName = "$(ProjectName)_d"
-OtherLinkFlags = "./libBeefRT_d.a ./libIDEHelper_d.dylib ./libBeefySysLib_d.dylib ../../extern/llvm_linux_8_0_0/lib/libLLVMCore.a ../../extern/llvm_linux_8_0_0/lib/libLLVMMC.a ../../extern/llvm_linux_8_0_0/lib/libLLVMMCParser.a ../../extern/llvm_linux_8_0_0/lib/libLLVMCodeGen.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86Disassembler.a ../../extern/llvm_linux_8_0_0/lib/libLLVMMCDisassembler.a ../../extern/llvm_linux_8_0_0/lib/libLLVMSupport.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86Info.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86Utils.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86AsmPrinter.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86Desc.a ../../extern/llvm_linux_8_0_0/lib/libLLVMObject.a ../../extern/llvm_linux_8_0_0/lib/libLLVMBitReader.a ../../extern/llvm_linux_8_0_0/lib/libLLVMAsmParser.a ../../extern/llvm_linux_8_0_0/lib/libLLVMTarget.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86CodeGen.a ../../extern/llvm_linux_8_0_0/lib/libLLVMScalarOpts.a ../../extern/llvm_linux_8_0_0/lib/libLLVMInstCombine.a ../../extern/llvm_linux_8_0_0/lib/libLLVMSelectionDAG.a ../../extern/llvm_linux_8_0_0/lib/libLLVMProfileData.a ../../extern/llvm_linux_8_0_0/lib/libLLVMTransformUtils.a ../../extern/llvm_linux_8_0_0/lib/libLLVMAnalysis.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86AsmParser.a ../../extern/llvm_linux_8_0_0/lib/libLLVMAsmPrinter.a ../../extern/llvm_linux_8_0_0/lib/libLLVMBitWriter.a ../../extern/llvm_linux_8_0_0/lib/libLLVMVectorize.a ../../extern/llvm_linux_8_0_0/lib/libLLVMipo.a ../../extern/llvm_linux_8_0_0/lib/libLLVMInstrumentation.a ../../extern/llvm_linux_8_0_0/lib/libLLVMDebugInfoDWARF.a ../../extern/llvm_linux_8_0_0/lib/libLLVMDebugInfoPDB.a ../../extern/llvm_linux_8_0_0/lib/libLLVMDebugInfoCodeView.a ../../extern/llvm_linux_8_0_0/lib/libLLVMGlobalISel.a ../../extern/llvm_linux_8_0_0/lib/libLLVMBinaryFormat.a ../../extern/llvm_linux_8_0_0/lib/libLLVMDemangle.a -Wl,-rpath -Wl,@executable_path"
+OtherLinkFlags = "./libBeefRT_d.a ./libIDEHelper_d.dylib ./libBeefySysLib_d.dylib ../../extern/llvm_linux_8_0_0/lib/libLLVMCore.a ../../extern/llvm_linux_8_0_0/lib/libLLVMMC.a ../../extern/llvm_linux_8_0_0/lib/libLLVMMCParser.a ../../extern/llvm_linux_8_0_0/lib/libLLVMCodeGen.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86Disassembler.a ../../extern/llvm_linux_8_0_0/lib/libLLVMMCDisassembler.a ../../extern/llvm_linux_8_0_0/lib/libLLVMSupport.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86Info.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86Utils.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86AsmPrinter.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86Desc.a ../../extern/llvm_linux_8_0_0/lib/libLLVMObject.a ../../extern/llvm_linux_8_0_0/lib/libLLVMBitReader.a ../../extern/llvm_linux_8_0_0/lib/libLLVMAsmParser.a ../../extern/llvm_linux_8_0_0/lib/libLLVMTarget.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86CodeGen.a ../../extern/llvm_linux_8_0_0/lib/libLLVMScalarOpts.a ../../extern/llvm_linux_8_0_0/lib/libLLVMInstCombine.a ../../extern/llvm_linux_8_0_0/lib/libLLVMSelectionDAG.a ../../extern/llvm_linux_8_0_0/lib/libLLVMProfileData.a ../../extern/llvm_linux_8_0_0/lib/libLLVMTransformUtils.a ../../extern/llvm_linux_8_0_0/lib/libLLVMAnalysis.a ../../extern/llvm_linux_8_0_0/lib/libLLVMX86AsmParser.a ../../extern/llvm_linux_8_0_0/lib/libLLVMAsmPrinter.a ../../extern/llvm_linux_8_0_0/lib/libLLVMBitWriter.a ../../extern/llvm_linux_8_0_0/lib/libLLVMVectorize.a ../../extern/llvm_linux_8_0_0/lib/libLLVMipo.a ../../extern/llvm_linux_8_0_0/lib/libLLVMInstrumentation.a ../../extern/llvm_linux_8_0_0/lib/libLLVMDebugInfoDWARF.a ../../extern/llvm_linux_8_0_0/lib/libLLVMDebugInfoPDB.a ../../extern/llvm_linux_8_0_0/lib/libLLVMDebugInfoCodeView.a ../../extern/llvm_linux_8_0_0/lib/libLLVMGlobalISel.a ../../extern/llvm_linux_8_0_0/lib/libLLVMBinaryFormat.a ../../extern/llvm_linux_8_0_0/lib/libLLVMDemangle.a /usr/local/opt/libffi/lib/libffi.a -Wl,-rpath -Wl,@executable_path"
 CLibType = "Dynamic"
 DebugCommandArguments = "-proddir=..\\ -config=Debug -platform=Win64"
 DebugWorkingDirectory = "$(WorkspaceDir)/../IDE/dist"
```

**Comment by bfiete** [comment]
Okay-I made some more fixes to the build, including a PR from @pmysl, which I do believe actually solves the macOS build issues!

**Comment by phillvancejr** [comment]
Works now, thank you!

**Comment by patgarner** [comment]
Yes! I was able to build as well!
